### ISSUE TITLE
[REQUEST] Support TinyMCE

### ISSUE THREAD

**Issue by iotech-fvtt** [dovrosenberg/fvtt-autocomplete-mentions#2]
Request you support TinyMCE as well as ProseMirror (and maybe Markdown too?). Prosemirror still is not nearly in feature parity with TinyMCE, so still using Tiny. 

Thanks for a GREAT mod!

**Comment by dovrosenberg** [comment]
Thanks for the note!  TinyMCE now supported in v1.0.0.

I'm going to close this issue to separate Tiny from others, but if you need Markdown (or something else), just open a new one with the editor needed and ideally a module that uses it so I can make sure I'm testing it correctly.
